//# Grammar and parser for the infix notation of basic calculator
//# ================

?start: expr

?expr: expr term ";" -> expr_more
     | term ";"      -> expr_one

?term: term "+" int -> plus
     | term "-" int -> minus
     | term "*" int -> times
     | term "/" int -> divide
     | int

%import common.WS
%import common.WS_INLINE
%import common.INT -> int
%ignore WS
%ignore WS_INLINE
//# /^([+-]?[1-9]\d*|0)$/
